# -*- coding: utf-8 -*-
"""seaborn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iqMe_AMGbomAH9DI9FjL9N1iFL9PAJ40
"""

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

import numpy as np
np.genfromtxt('data.csv', delimiter = ',')

np.eye((5))

np.abs

np.abs(np.eye((5)))

arr = np.array([(1,2,3),(4,5,6),(7,8,9)])
arr[0:3,2]

arr < 5
ara = np.eye((6))
ar = ara < 1
ara[ara<1]

import pandas as pd
x = pd.read_html('https://www.google.co.in/')
x

pd

!wget https://github.com/mwaskom/seaborn-data/blob/master/titanic.csv

!ls

pd.read_csv('titanic.csv.1')

ls

import matplotlib.pyplot as plt
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic

sns.factorplot(titanic['sex'], titanic['survived'], data=titanic,kind="bar",palette="Blues",size=6,aspect=2,legend_out=False);

import pandas as pd
import seaborn as sb
from matplotlib import pyplot as plt
df = sb.load_dataset('titanic')
sb.barplot(x = "sex", y = "survived", hue = "class", data = df)
plt.show()

"""2. Write a program to draw a barplot to show count for a deck for a dataset given in the url
**bold text**
"""

# !wget https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv
!ls

import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt
df = sb.load_dataset('titanic')
sb.countplot(x='class', data = df , palette = 'b')
plt.show()

"""Write a program to draw a point plot for sex against survived for a dataset given in url"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
df = sb.load_dataset('titanic')
sb.pointplot(x = 'sex', y = 'survived', data= df,hue = "class")
plt.show()

"""Seaborn Scatterplot
Write a program to draw a scatter plot of “day” against “total bill” for a dataset given in a url
"""

!wget  https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
df = sb.load_dataset('tips')
sb.stripplot(x="day", y="total_bill",data=df) 
plt.show()

"""Write a program to draw a violin plot of sex against day  for a  given dataset"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
df = sb.load_dataset('tips')
sb.violinplot(x="time", y="sex",data=df) 
plt.show()

"""2.  Write a program to draw a violin plot of “species” against “sepal length” for a dataset given in a url"""

!wget https://github.com/mwaskom/seaborn-data/blob/master/iris.csv

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
df = sb.load_dataset('iris')
sb.violinplot(x="species", y="sepal_length",data=df) 
plt.show()

!wget https://raw.githubusercontent.com/resbaz/r-novice-gapminder-files/master/data/gapminder-FiveYearData.csv

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
df = sb.load_dataset('gapminder-FiveYearData')
sb.boxplot(x="continent", y="lifeExp",data=df) 
plt.show()

"""Write a program to draw box plot of life expectancy by continent for a data set given in a url"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
df = sb.load_dataset('tips')
sb.boxplot(x="day", y="tip",data=df) 
plt.show()



"""Write a program to draw a swarm plot of total bill against size  for a  given dataset"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
df = sb.load_dataset('tips')
sb.swarmplot(x='total_bill', y = 'size', data =df)
plt.show()

""". Write a program to draw swarm plot of “total bill” against day for a dataset given in url"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
df = sb.load_dataset('tips')
sb.swarmplot(x='total_bill', y = 'day', data =df)
plt.show()

"""1. Write a program to draw a scatter plot for random 1000 x and y coordinates"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
x = [np.random.randint(1000)]
y = [np.random.randint(1000)]
sb.scatterplot(x, y)
plt.show()

"""2. Write a program to draw line and scatter plots for random 100 x and y coordinates"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
x = [np.random.randint(100)]
y = [np.random.randint(100)]
sb.lineplot(x, y)
plt.show()

!sudo apt-get update

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
x = [np.random.randint(500)]
y = [np.random.randint(500)]
sb.lineplot(x, y)
plt.show()

"""4. Write a program to draw a scatter plot for a given dataset and show datalabels on hover"""

!pip install seaborn

